name = "AI: DilliDalli"
uid = "28F4B5A9EDE30F06-version:1.0.0"
version = 9
copyright = "Softles"
description = "ALPHA version - complete AI code rewrite.  Builds more tanks."
author = "Softles"
url = "https://github.com/HardlySoftly/DilliDalli"
icon = "/mods/DilliDalli/bugfix.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
