name = "AI: DilliDalli"
uid = "28F4B5A9EDE30F06-version:0.0.6"
version = 0
copyright = "Softles"
description = "There are 10 types of people in the world:  01) Those that understand binary; 02) Those that don't; 10) And those that didn't expect this joke to be in base three."
author = "Softles"
url = "https://github.com/HardlySoftly/DilliDalli"
icon = "/mods/DilliDalli/bugfix.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
