name = "AI: DilliDalli"
uid = "28F4B5A9EDE30F06-version:0.2.10"
version = 5
copyright = "Softles"
description = "ALPHA version: 1v1 specialist AI.  Complete AI code rewrite."
author = "Softles"
url = "https://github.com/HardlySoftly/DilliDalli"
icon = "/mods/DilliDalli/bugfix.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
