translate = {
    MexT1 = {
        AEON = "uab1103",
        UEF = "ueb1103",
        CYBRAN = "urb1103",
        SERAPHIM = "xsb1103",
        NOMADS = "xnb1103",
        ARM = "armmex",
        CORE = "cormex",
    },
    MexT2 = {
        AEON = "uab1202",
        UEF = "ueb1202",
        CYBRAN = "urb1202",
        SERAPHIM = "xsb1202",
        NOMADS = "xnb1202",
        ARM = "armmass",
        CORE = "cormass",
    },
    MexT3 = {
        AEON = "uab1302",
        UEF = "ueb1302",
        CYBRAN = "urb1302",
        SERAPHIM = "xsb1302",
        NOMADS = "xnb1302",
        ARM = "armmoho",
        CORE = "cormoho",
    },
    LandFactoryT1 = {
        AEON = "uab0101",
        UEF = "ueb0101",
        CYBRAN = "urb0101",
        SERAPHIM = "xsb0101",
        NOMADS = "xnb0101",
        ARM = "armlab",
        CORE = "corvp",
    },
    LandHQT2 = {
        AEON = "uab0201",
        UEF = "ueb0201",
        CYBRAN = "urb0201",
        SERAPHIM = "xsb0201",
        NOMADS = "xnb0201",
        ARM = "armdlab",
        CORE = "cordvp",
    },
    LandHQT3 = {
        AEON = "uab0301",
        UEF = "ueb0301",
        CYBRAN = "urb0301",
        SERAPHIM = "xsb0301",
        NOMADS = "xnb0301",
        ARM = "armadlab",
        CORE = "coradvp",
    },
    LandSupportT2 = {
        AEON = "zab9501",
        UEF = "zeb9501",
        CYBRAN = "zrb9501",
        SERAPHIM = "zsb9501",
        NOMADS = "znb9501",
        ARM = "armalab",
        CORE = "coravp",
    },
    LandSupportT3 = {
        AEON = "zab9601",
        UEF = "zeb9601",
        CYBRAN = "zrb9601",
        SERAPHIM = "zsb9601",
        NOMADS = "znb9601",
        ARM = "armhp",
        CORE = "corhp",
    },
    AirFactoryT1 = {
        AEON = "uab0102",
        UEF = "ueb0102",
        CYBRAN = "urb0102",
        SERAPHIM = "xsb0102",
        NOMADS = "xnb0102",
        ARM = "armap",
        CORE = "corap",
    },
    AirHQT2 = {
        AEON = "uab0202",
        UEF = "ueb0202",
        CYBRAN = "urb0202",
        SERAPHIM = "xsb0202",
        NOMADS = "xnb0202",
        ARM = "armdap",
        CORE = "cordap",
    },
    AirHQT3 = {
        AEON = "uab0302",
        UEF = "ueb0302",
        CYBRAN = "urb0302",
        SERAPHIM = "xsb0302",
        NOMADS = "xnb0302",
        ARM = "armdap",
        CORE = "cordap",
    },
    AirSupportT2 = {
        AEON = "zab9502",
        UEF = "zeb9502",
        CYBRAN = "zrb9502",
        SERAPHIM = "zsb9502",
        NOMADS = "znb9502",
        ARM = "armaap",
        CORE = "coraap",
    },
    AirSupportT3 = {
        AEON = "zab9602",
        UEF = "zeb9602",
        CYBRAN = "zrb9602",
        SERAPHIM = "zsb9602",
        NOMADS = "znb9602",
        ARM = "armplat",
        CORE = "corplat",
    },
    Hydro = {
        AEON = "uab1102",
        UEF = "ueb1102",
        CYBRAN = "urb1102",
        SERAPHIM = "xsb1102",
        NOMADS = "xnb1102",
        ARM = "armgeo",
        CORE = "corgeo",
    },
    PgenT1 = {
        AEON = "uab1101",
        UEF = "ueb1101",
        CYBRAN = "urb1101",
        SERAPHIM = "xsb1101",
        NOMADS = "xnb1101",
        ARM = "armsolar",
        CORE = "corsolar",
    },
    PgenT2 = {
        AEON = "uab1201",
        UEF = "ueb1201",
        CYBRAN = "urb1201",
        SERAPHIM = "xsb1201",
        NOMADS = "xnb1201",
        ARM = "armfus",
        CORE = "corfus",
    },
    PgenT3 = {
        AEON = "uab1301",
        UEF = "ueb1301",
        CYBRAN = "urb1301",
        SERAPHIM = "xsb1301",
        NOMADS = "xnb1301",
        ARM = "armckfus",
        CORE = "corckfus",
    },
    EngineerT1 = {
        AEON = "ual0105",
        UEF = "uel0105",
        CYBRAN = "url0105",
        SERAPHIM = "xsl0105",
        NOMADS = "xnl0105",
        ARM = "armck",
        CORE = "corcv",
    },
    EngineerT2 = {
        AEON = "ual0208",
        UEF = "uel0208",
        CYBRAN = "url0208",
        SERAPHIM = "xsl0208",
        NOMADS = "xnl0208",
        ARM = "armack",
        CORE = "coracv",
    },
    EngineerT3 = {
        AEON = "ual0309",
        UEF = "uel0309",
        CYBRAN = "url0309",
        SERAPHIM = "xsl0309",
        NOMADS = "xnl0309",
        ARM = "armch",
        CORE = "corch",
    },
    LandScoutT1 = {
        AEON = "ual0101",
        UEF = "uel0101",
        CYBRAN = "url0101",
        SERAPHIM = "xsl0101",
        NOMADS = "xnl0101",
        ARM = "armflea",
        CORE = "corfav",
    },
    DirectFireT1 = {
        AEON = "ual0201",
        UEF = "uel0201",
        CYBRAN = "url0107",
        SERAPHIM = "xsl0201",
        NOMADS = "xnl0201",
        ARM = "armwar",
        CORE = "corraid",
    },
    ArtyT1 = {
        AEON = "ual0103",
        UEF = "uel0103",
        CYBRAN = "url0103",
        SERAPHIM = "xsl0103",
        NOMADS = "xnl0107",
        ARM = "armham",
        CORE = "corlevlr",
    },
    AntiAirT1 = {
        AEON = "ual0104",
        UEF = "uel0104",
        CYBRAN = "url0104",
        SERAPHIM = "xsl0104",
        NOMADS = "xnl0103",
        ARM = "armjeth",
        CORE = "cormist",
    },
    DirectFireT2 = {
        AEON = "ual0202",
        UEF = "uel0202",
        CYBRAN = "url0202",
        SERAPHIM = "xsl0202",
        NOMADS = "xnl0202",
        ARM = "armfido",
        CORE = "correap",
    },
    RangedT2 = {
        AEON = "xal0203",
        UEF = "del0204",
        CYBRAN = "drl0204",
        SERAPHIM = "xsl0202",
        NOMADS = "xnl0306",
        ARM = "armfast",
        CORE = "corseal",
    },
    AmphibiousT2 = {
        AEON = "xal0203",
        UEF = "uel0203",
        CYBRAN = "url0203",
        SERAPHIM = "xsl0203",
        NOMADS = "xnl0203",
        ARM = "armamph",
        CORE = "corseal",
    },
    AntiAirT2 = {
        AEON = "ual0205",
        UEF = "uel0205",
        CYBRAN = "url0205",
        SERAPHIM = "xsl0205",
        NOMADS = "xnl0205",
        ARM = "armamph",
        CORE = "corsent",
    },
    MMLT2 = {
        AEON = "ual0111",
        UEF = "uel0111",
        CYBRAN = "url0111",
        SERAPHIM = "xsl0111",
        NOMADS = "xnl0111",
        ARM = "armrock",
        CORE = "corvroc",
    },
    DirectFireT3 = {
        AEON = "ual0303",
        UEF = "uel0303",
        CYBRAN = "url0303",
        SERAPHIM = "xsl0303",
        NOMADS = "xnl0303",
        ARM = "armzeus",
        CORE = "corgol",
    },
    RangedT3 = {
        AEON = "xal0305",
        UEF = "xel0305",
        CYBRAN = "xrl0305",
        SERAPHIM = "xsl0305",
        NOMADS = "xnl0305",
        ARM = "armsnipe",
        CORE = "cormort",
    },
    HeavyLandT3 = {
        AEON = "ual0303",
        UEF = "xel0305",
        CYBRAN = "xrl0305",
        SERAPHIM = "xsl0303",
        NOMADS = "xnl0305",
        ARM = "armanac",
        CORE = "corsnap",
    },
    AntiAirT3 = {
        AEON = "dalk003",
        UEF = "delk002",
        CYBRAN = "drlk001",
        SERAPHIM = "dslk004",
        NOMADS = "xnl0302",
        ARM = "armah",
        CORE = "corah",
    },
    ArtyT3 = {
        AEON = "ual0304",
        UEF = "uel0304",
        CYBRAN = "url0304",
        SERAPHIM = "xsl0304",
        NOMADS = "xnl0304",
        ARM = "armbrtha",
        CORE = "corint",
    },
    LandExp = {
        AEON = "ual0401",
        UEF = "uel0401",
        CYBRAN = "url0402",
        SERAPHIM = "xsl0401",
        NOMADS = "xnl0403",
        ARM = "armdrake",
        CORE = "corkrog",
    },
    AirScoutT1 = {
        AEON = "uaa0101",
        UEF = "uea0101",
        CYBRAN = "ura0101",
        SERAPHIM = "xsa0101",
        NOMADS = "xna0101",
        ARM = "armpeep",
        CORE = "corfink",
    },
    IntieT1 = {
        AEON = "uaa0102",
        UEF = "uea0102",
        CYBRAN = "ura0102",
        SERAPHIM = "xsa0102",
        NOMADS = "xna0102",
        ARM = "armfig",
        CORE = "corveng",
    },
}